### ISSUE TITLE
MANIFEST.in paths not separated by /

### ISSUE THREAD

**Issue by jlfsjunior** [elephaint/pgbm#14]
**Describe the bug**
First of all, thanks for this nice package and for providing many examples. 

The paths in MANIFEST.in are written in Win format (with \ separator), therefore ignored when installing from source in Unix. 

From the [MANIFEST.in docs](https://packaging.python.org/en/latest/guides/using-manifest-in/):

>File & directory names in MANIFEST.in should be /-separated; setuptools will automatically convert the slashes to the local platform’s appropriate directory separator.

**To Reproduce**
1. On linux, install from source via `python setup.py install`

2. Warning are logged during installation:

```sh
reading manifest template 'MANIFEST.in'
warning: no files found matching 'src\pgbm\splitgain_cpu.cpp'
warning: no files found matching 'src\pgbm\splitgain_cuda.cpp'
warning: no files found matching 'src\pgbm\splitgain_kernel.cu'
warning: no files found matching 'src\pgbm_dist\parallelsum.cpp'
warning: no files found matching 'src\pgbm_dist\parallelsum_kernel.cu'
```

 3. Run the [first example](https://github.com/elephaint/pgbm/blob/main/examples/pytorch/example01_housing_cpu.py) will return an error:
```sh
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/site-packages/pgbm/splitgain_cpu.cpp'
```

**Comment by elephaint** [comment]
Hi,

Thanks for reporting. Didn't know that. I'll fix it right away!

**Comment by elephaint** [comment]
Hi, 

Fixed it, should work now. Weird that it did not work for you, since we have Github actions checking compliance on Linux installations which gave no complaints (?)
