### ISSUE TITLE
Puzzling to see such methods - it is proven they don't work

### ISSUE THREAD

**Issue by valeman** [elephaint/pgbm#28]
Puzzling to see such methods - it is proven they don't work. Relying on normality assumptions and parametric methods can not produce good prediction intervals.

https://medium.com/@valeman/does-ngboost-work-evaluating-ngboost-against-critical-criteria-for-good-probabilistic-prediction-28c4871c1bab

**Comment by elephaint** [comment]
I agree! That's why PGBM doesn't rely on a normality assumption.

I'm not sure what the issue is, though?
